### ISSUE TITLE
DefaultAnimations in UWP

### ISSUE THREAD

**Issue by luisllamasbinaburo** [XamlFlair/XamlFlair#43]
Hi, 

Is is posible to have the same DefaultAnimations in UWP than WPF, using this as UWP resource URL

```xaml
<!-- UWP -->
<ResourceDictionary Source="ms-appx:///XamlFlair.UWP/DefaultAnimations.xaml" />
```

I included this in a previous commit, but I think you didn't see it, and at some point some code mixed and overwrite that.
(in fact, now the readme is not correct, it mix WPF and UWP path)

**Comment by XamlFlair** [comment]
hi @luisllamasbinaburo, I actually had to remove it along with the 10 ms delay because I had experienced problems. WPF worked fine so I kept them in WPF, but in UWP it wasn't compiling. Concerning the 10ms delay, the change was too global, it affected every animation that gets created. I was wondering if you can make the delay directly on your animations in xaml where they flicker?

**Comment by luisllamasbinaburo** [comment]
Ok, I understood about the delay change. I will look for a workaround in the future.

But DefaultAnimations in UWP is compiling for me.
Could you test the PR i have just make, please?

**Comment by XamlFlair** [comment]
I will close this issue but I have a branch for myself to work on hopefully soon.👍
