### ISSUE TITLE
Offset must be a double or a star-based value (ex: 150 or 0.75*).

### ISSUE THREAD

**Issue by GF-Huang** [XamlFlair/XamlFlair#88]
Hello, I used `XamlFlair` in my product, my customer send me a error report (seems was Czech language environment). But I can't reproduce on my machine (Chinese language environment).

![image](https://user-images.githubusercontent.com/4510984/126997088-750214a7-9381-42ce-a769-0b684ea27cbe.png)

The exception from:
https://github.com/XamlFlair/XamlFlair/blob/5a6a111a6072914423e420d8edeb10d9ed783966/XamlFlair.Shared/Entities/Offset.cs#L85

I read the source code, it seems skip the second `if` condition, it's very strange.

https://github.com/XamlFlair/XamlFlair/blob/5a6a111a6072914423e420d8edeb10d9ed783966/XamlFlair.Shared/Entities/Offset.cs#L70-L76

And these are all my codes which reference `OffsetY=-0.75*`.

![image](https://user-images.githubusercontent.com/4510984/126997705-c96e8634-f3c4-40bb-a249-881de34ea1f0.png)

Version: `XamlFlair.WPF 1.2.8`
OS: `Win 10.0.19042.0`
.NET: `5.0.8`

Any suggestions?

**Comment by assassin316** [comment]
@GF-Huang  thanks for reporting this, looking at the bug, since he's in Czech, I think I may know what the problem is, I will have to debug it. These are the regional settings for a Czech machine:

![image](https://user-images.githubusercontent.com/17514380/127000161-b92c40bb-cd75-4ef3-be66-f65054f70272.png)

It seems that the 0.75 is expected as 0,75 in Czech. I will have to change the string comparison code to factor that in. I'll come back to you with an update as soon as I can.

**Comment by XamlFlair** [comment]
@GF-Huang  issue was reproduced locally and I applied a fix. A release will be pushed within the next day. 👍

**Comment by GF-Huang** [comment]
> @GF-Huang issue was reproduced locally and I applied a fix. A release will be pushed within the next day. 👍

Great, thanks your quick fix.

**Comment by XamlFlair** [comment]
@GF-Huang

**Comment by XamlFlair** [comment]
@GF-Huang you can go ahead and grab the latest version. Let me know if it's fixed.

**Comment by GF-Huang** [comment]
> @GF-Huang you can go ahead and grab the latest version. Let me know if it's fixed.

It's fixed, thank you.
